# Generated by Django 3.1.7 on 2021-03-03 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_shop_blablabla'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.shop', verbose_name='Shop'),
            preserve_default=False,
        ),
    ]
